language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip
script:
  - go test ./...
  - go build
install:
  - go get -v github.com/stretchr/testify
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - goveralls -v -service travis-ci -repotoken $COVERALLS_TOKEN
